- hosts: localhost
  tags: always
  become: false

  pre_tasks:
    - import_tasks: playbooks/whoami.yml
    - import_tasks: playbooks/whoami_debug.yml

  roles:
    - role: base
      tags: base

    - role: workstation
      tags: workstation
      when: Setup == "1"

    - role: server
      tags: server
      when: Setup == "2"
