- hosts: localhost
  tags: always
  become: false

  pre_tasks:
    - import_tasks: Pre-Tasks/whoami.yml
    - import_tasks: Pre-Tasks/whoami_debug.yml
    - import_tasks: Pre-Tasks/temp_pass.yml
    - import_tasks: Pre-Tasks/update_packages.yml
    - import_tasks: Pre-Tasks/dependencies.yml

  roles:
    - role: base
      tags: base

    - role: workstation
      tags: workstation
      when: Setup == "1"

    - role: server
      tags: server
      when: Setup == "2"

    - role: dotfiles
      tags: dotfiles
  tasks:
    # - import_tasks: Post-Tasks/temp_remove.yml
# Game Plan
# Here some notes that I want to Do now I think
# 2. Download dotfiles
# 3. Base Files
# - download packages
# 4. Do Workstation
# - Use the end_4 dots script to install
# - edit end_4 dots to my personal conf
# - add what ever other packages I want
# - remove unwanted packages
# 5. Do Server?
# - idk figure this out later when I need to rebuild a server
# - manily just download docker
# 7. Add Dotfiles
# 8. Remove temp user
