- hosts: localhost
  tags: always
  become: false

  pre_tasks:
    - name: Pre-Tasks
      block:
        - import_tasks: playbooks/whoami.yml
        - import_tasks: playbooks/update.yml

        - name: Pre-Tasks | DEBUG SETUP TEST
          tags: debug
          debug:
            msg: "{{ Setup }}"
        - name: Pre-Tasks | DEBUG NAME
          tags: debug
          debug:
            msg: "{{ username }}"
        - name: Pre-Tasks | DEBUG DIR
          tags: debug
          debug:
            msg: "{{ user_dir}}"
        - name: Pre-Tasks | DEBUG OS
          tags: debug
          debug:
            msg: "{{ distribution }}"
  roles:
    - role: base
      tags: base

    - role: workstation
      tags: workstation
      when: Setup == "1"

    - role: server
      tags: server
      when: Setup == "2"

  # - name: create .config if not already present
  #   ansible.builtin.file:
  #     path: ~/.config
  #     state: directory
  #     mode: "0755"

  # - name: Register Current User
  #   ansible.builtin.set_fact:
  #     host_user: "{{ ansible_env['USER']}}"
