- hosts: localhost
  connection: local
  become: false 

  tasks:
  - name: Install Packages
    become: true
    pacman:
     name: 
      - ansible
      - fzf
      - less
      - otf-firamono-nerd
      # - PulseAudio Later
      - stow
      - tree
      # - yay Later
      - zoxide
      - zsh
      # - zen Later

  - name: Clone a dotfiles repo
    become: false #Has to be non Sudo so that we can user the right home folder
    git:
      repo: https://github.com/TriforceGB/dotfiles.git
      dest: "~/dotfiles"
      clone: yes
      update: yes
  
  # - name: test directory
  #   file:
  #     path: "~/test"
  #     state: directory
  #     mode: 0755