- hosts: localhost
  connection: local
  become: false 
  vars:
    the_user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: update repository
      become: true
      pacman: 
        update_cache: true
        upgrade: true
        
    - name: create .config if not already present
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: '0755'


  tasks:
    - include: playbooks/pacman.yml
    - include: playbooks/dotfiles.yml