- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Packages
    pacman:
     name: 
      - ansible
      - fzf
      - less
      - otf-firamono-nerd
      # - PulseAudio Later
      - stow
      - tree
      # - yay Later
      - zoxide
      - zsh
      # - zen Later

  - name: Clone a dotfiles repo
    git:
      repo: https://github.com/TriforceGB/dotfiles.git
      dest: ~/dotfiles