- hosts: localhost
  connection: local
  become: false 
  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
  - name: Install Packages
    become: true
    pacman:
     name: 
      - ansible
      - fzf
      - less
      - otf-firamono-nerd
      # - PulseAudio Later
      - stow
      - tree
      # - yay Later
      - zoxide
      - zsh
      # - zen Later

  - name: Clone a dotfiles repo
    become: false #Has to be non Sudo so that we can user the right home folder
    git:
      repo: https://github.com/TriforceGB/dotfiles.git
      dest: "~/dotfiles"
      clone: yes
      update: yes
      
  - name: Run stow to manage dotfiles
    become: false #Has to be non Sudo so that we can user the right home folder
    ansible.builtin.shell:
      cmd: 'stow .'
      chdir: '~/dotfiles'  # Replace with your stow directory

  - name: change user shell to zsh 
    become: true
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
  
  # - name: test directory
  #   file:
  #     path: "~/test"
  #     state: directory
  #     mode: 0755