- hosts: localhost
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"

  pre_tasks:
    - name: update repository
      become: true
      pacman:
        update_cache: true
        upgrade: true

    - name: create .config if not already present
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: "0755"

    - name: Register Current User
      ansible.builtin.set_fact:
        host_user: "{{ ansible_env['USER']}}"

    - name: DEBUG
      ansible.builtin.debug:
        msg: "{{ host_user }}"
    - name: User Dir
      ansible.builtin.debug:
        msg: "{{ user_dir }}"
  tasks:
    - import_tasks: playbooks/packages.yml
    - import_tasks: playbooks/dotfiles.yml
