- name: workstation | hyprland | Remove Unwanted Packages
  pacman:
    state: absent
    name: 
      - fish
      - foot
- name: workstation | hyprland | Remove hypr config
  file:
    path: ~/.config/hypr
    state: absent
- name: workstation | hyprland | Remove fish config
  file:
    path: ~/.config/fish
    state: absent

#files I want to Remove
# fish config
# /hypr/
# nautlilus?
#