- name: Base | zsh | Stow dotfiles
  tags: zsh,dotfiles
  become: false
  shell:
    cmd: "stow zsh"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Base | zsh | Change Default Shell
  tags: zsh
  become: true
  user: 
    name: "{{ username }}"
    shell: /bin/zsh

- name: nvim | Stow Dotfiles
  tags: nvim,dotfiles
  become: false
  shell:
    cmd: "stow nvim"
    chdir: "{{ user_dir }}/.dotfiles/"

# - name: Base | fastfetch | Stow dotfiles
#   become: false
#   shell:
#     cmd: "stow fastfetch"
#     chdir: "{{ user_dir }}/.dotfiles/"