- import_tasks: /Archlinux.yml


- name: workstation | Announcement
  tags: always
  debug:
    msg: WE are Base
- name: workstation | DEBUG NAME
  tags: always
  debug:
    msg: "{{ username }}"
# terminal elmulator
# file manager
# discord
# obsidian
