- name: Base | Arch | Update pacman.conf
  tags: arch,pacman
  become: true
  copy:
    src: files/pacman.conf
    dest: /etc/pacman.conf"

- name: Base | Arch | Update Package 
  tags: arch,update,package
  become: true
  pacman:
    update_cache: true
    upgrade: true

- block:
    - name: Base | Arch | Clone yay repo
      become: false
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "/tmp/yay"
        clone: yes

    - name:  Base | Arch | Install yay
      become: false
      command: 
        cmd: makepkg -sfi --noconfirm 
        chdir: "/tmp/yay"

    - name: Base | Arch | Remove yay build directory
      file:
        path: "/tmp/yay"
        state: absent