- name: nvim | pacman Install
  become: true
  pacman:
    name: 
      - vim
      - neovim
  when: distribution == "Archlinux"

- name: nvim | Stow Dotfiles
  become: false
  shell:
    cmd: "stow nvim"
    chdir: "{{ user_dir }}/.dotfiles/"