- name: Base | zsh | Pacman zsh & Dependencies
  become: true
  pacman:
    name: 
      - zsh
      - zoxide
      - otf-firamono-nerd
      - fzf
  when: distribution == "Archlinux"

- name: Base | zsh | Stow dotfiles
  become: false
  shell:
    cmd: "stow zsh"
    chdir: "{{ user_dir }}/.dotfiles/"

- name: Base | zsh | Change Default Shell
  become: true
  user: 
    name: "{{ username }}"
    shell: /bin/zsh