- name: Base | Arch | Install zsh & Dependencies
  become: true
  pacman:
    name: 
      - zsh
      - zoxide
      - otf-firamono-nerd
      - fzf
  when: distribution == "Archlinux"

- name: Base | Stow | zsh dotfiles
  become: false
  shell:
    cmd: "stow zsh"
    chdir: "{{ user_dir }}/.dotfiles/"