- name: Clone a dotfiles repo
  become: false #Has to be non Sudo so that we can user the right home folder
  git:
    repo: https://github.com/TriforceGB/dotfiles.git
    dest: "~/dotfiles"
    clone: yes
    update: yes
    
- name: Run stow to manage dotfiles
  become: false #Has to be non Sudo so that we can user the right home folder
  shell: 
    cmd: 'stow .'
    chdir: '~/dotfiles'  # Replace with your stow directory

- name: change user shell to zsh 
  become: true
  user: 
    name: "{{ the_user }}"
    shell: /bin/zsh
