- name: Install Packages
  become: true
  pacman:
    name: 
      - ansible
      - fzf
      - less
      - otf-firamono-nerd
      # - PulseAudio Later
      - stow
      - tree
      # - yay Later
      - zoxide
      - zsh
      # - zen Later