- name: Pre-Tasks | DEBUG SETUP TEST
  tags: debug
  debug:
    msg: "{{ Setup }}"

- name: Pre-Tasks | DEBUG NAME
  tags: debug
  debug:
    msg: "{{ username }}"

- name: Pre-Tasks | DEBUG DIR
  tags: debug
  debug:
    msg: "{{ user_dir}}"

- name: Pre-Tasks | DEBUG OS
  tags: debug
  debug:
    msg: "{{ distribution }}"
