- name: Dotfiles | Clone Dotfiles Repo
  become: false #Has to be non Sudo so that we can user the right home folder
  tags: git,dotfiles
  git:
    repo: https://github.com/TriforceGB/.dotfiles.git
    dest: "~/.dotfiles"
    clone: yes
    update: yes

- name: Dotfiles | Create .config
  file:
    path: "{{user_dir}}/.config"
    state: directory
    mode: "0755"