- name: Git | Set Global Username
  tags: git
  git_config:
    name: user.name
    value: "{{ username }}" 
    scope: global 

- name: Git | Set Global Email
  tags: git
  git_config:
    name: user.email
    value: "Zach.Schultz.2.0.1@gmail.com" # My Email pull from Bitwarden Later?
    scope: global 

- name: Git | Set Global Default Branch
  tags: git
  git_config:
    name: init.defaultBranch
    value: main
    scope: global 

- name: Git | Set Stored Credentials
  tags: git
  git_config:
    name: credential.helper
    value: store
    scope: global  